org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx4g

kotlin.mpp.stability.nowarn=true
org.gradle.dependency.verification.console=verbose

org.gradle.caching=true
org.gradle.unsafe.configuration-cache=true
org.gradle.unsafe.configuration-cache-problems=warn
org.gradle.parallel=true
org.gradle.logging.stacktrace=all

org.gradle.kotlin.dsl.precompiled.accessors.strict=true
