version: "3.9"

services:
  kafka-pipe:
    image: dev-adamko/kafka-pipe/${KAFKATORIO_VERSION}
    container_name: "kafka-pipe"
    build:
      dockerfile: "kafka-pipe.Dockerfile"
      context: "."
    restart: "unless-stopped"
    privileged: true
    networks:
      - "kafkatorio-nw"
    environment:
      FACTORIO_SERVER_CONTAINER_NAME: "factorio-server"
      KAFKATORIO_VERSION: $KAFKATORIO_VERSION
      KAFKA_HOST: "kafka:29092"
    volumes:
      # Windows (requires privileged/root)
      - "//var/run/docker.sock:/var/run/docker.sock"
      # Unix?
      # - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  kafkatorio-nw:
    name: "kafkatorio-nw"
    external: true
