version: "3.9"

services:
  kafka-pipe:
    image: ${REGISTRY_HOST}/${APP_GROUP}/${APP_NAME}:${KAFKATORIO_VERSION}
    container_name: ${APP_NAME}
    build:
      dockerfile: "kafka-pipe.Dockerfile"
      context: "."
      args:
        APP_NAME: ${APP_NAME}
    restart: "unless-stopped"
    privileged: true
    networks:
      - "kafkatorio-nw"
    environment:
      KAFKATORIO_VERSION: $KAFKATORIO_VERSION
      # message IDs
      INSTANCE_ID: "test-server"
      # name of the docker container
      FACTORIO_SERVER_CONTAINER_NAME: "factorio-server"
      KAFKA_HOST: "kafka:29092"
    volumes:
      # Windows (requires privileged/root)
      - "//var/run/docker.sock:/var/run/docker.sock"

      # Rootless:
#      - "/run/user/1000/docker.sock:/var/run/docker.sock"

      # Unix?
      # - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  kafkatorio-nw:
    name: "kafkatorio-nw"
    external: true
