# Kafkatorio server config

jwt-secret: "correct horse battery staple"

# Define the servers that have the Kafkatorio Mod installed.
kafkatorio-servers:
  # The key is the short ID, used to uniquely identify a server (used in URLs).
  # The value is a description.
  short-id-123: "Name of server"
  another-id-456: "Name of another server"
