version: "3.9"

services:

  kafkatorio-web-map:
    image: adamko-dev/kafkatorio-web-map
    container_name: kafkatorio-web-map
    build:
      context: ".."
      dockerfile: ./docker/Dockerfile
    ports:
      - "12081:80"
    networks:
      - "kafkatorio-nw"

networks:
  kafkatorio-nw:
    name: "kafkatorio-nw"
    external: true
