version: "3.9"

services:

  kafkatorio-web-map:
    image: ${REGISTRY_HOST}/${APP_GROUP}/${APP_NAME}:${KAFKATORIO_VERSION}
    container_name: ${APP_NAME}
    restart: unless-stopped
    build:
      context: ".."
      dockerfile: ./docker/Dockerfile
      args:
        APP_NAME: ${APP_NAME}
    ports:
      - "12081:80"
    networks:
      - "kafkatorio-nw"
      - "traefik-nw"
    labels:
      - "traefik.enable=true"

networks:
  kafkatorio-nw:
    name: "kafkatorio-nw"
    external: true
  traefik-nw:
    name: "traefik-nw"
    external: true
