# Factorio Events Processor config

web-port: ${SERVER_PORT:-8080}
tile-dir: ${TILE_DIR:-./tile-dir}


socket-server-host: ${SOCKET_SERVER_HOST:-127.0.0.1}
socket-server-port: ${SOCKET_SERVER_PORT:-9002}


kafka-admin-config:
  client.id: kafkatorio.events-server-admin
  bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVERS:-http://localhost:9092}


kafka-streams-config:
  application.id: kafkatorio-events-processor
  bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVERS:-http://localhost:9092}
  state.dir: ${KAFKA_STREAMS_STATE_DIR:-./kafka-state}
  num.stream.threads: 1
  processing.guarantee: exactly_once_v2
  auto.offset.reset: earliest
  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde

  #      default.deserialization.exception.handler: org.apache.kafka.streams.errors.LogAndContinueExceptionHandler

  #buffered.records.per.partition: 0
  #poll.ms: 10000

  # 31457280 :  30MB
  max.request.size: 31457280
  buffer.memory: 31457280

  compression.type: snappy
  # linger.ms=5

  # fetch.message.max.bytes=31457280
  # 100mb 104857600


#kafka:
#  bootstrap-servers:
#    - "http://localhost:9092"
#  config: |
#    application.id=kafkatorio-events-processor
#    bootstrap.servers={{bootstrap-servers}}
#    state.dir=./kafka-state
#    num.stream.threads=1
#    processing.guarantee=exactly_once_v2
#    auto.offset.reset=earliest
#    default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
#    default.value.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
#    default.deserialization.exception.handler=org.apache.kafka.streams.errors.LogAndContinueExceptionHandler
#    #buffered.records.per.partition=0
#    #poll.ms=10000
#
#    # 31457280 = 30MB
#    max.request.size=31457280
#    buffer.memory=31457280
#
#    compression.type=snappy
#    # linger.ms=5
#
#    # fetch.message.max.bytes=31457280
#    # 100mb 104857600
#
#tileServer:
#  webmapTileDir: 'D:\Users\Adam\Projects\games\kafkatorio\modules\events-server\kafkatorio-tiles'
