version: "3.9"

services:
  kp2:
    image: openjdk:11-jre-buster
    container_name: "factorio-events-kafka-pipe"
    build:
      dockerfile: "kafka-pipe.Dockerfile"
    networks:
      - "factorio-events-nw"
    environment:
      FACTORIO_SERVER_CONTAINER_NAME: "factorio-server"
      KAFKA_HOST: "kafka:29092"
    volumes:
      # Windows (requires privileged/root)
      - "//var/run/docker.sock:/var/run/docker.sock"
      # Unix?
      # - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  factorio-events-nw:
    name: "factorio-events-nw"
    external: true
