version: "3.9"

services:

  kafka:
    image: dev-adamko/kafka-kraft
    container_name: "kafka"
    restart: "unless-stopped"
    build:
      dockerfile: "kafka.Dockerfile"
      target: "kafka-kraft"
      args:
        KAFKA_DL_URL: "https://dlcdn.apache.org/kafka/3.0.0/kafka_2.13-3.0.0.tgz"
    networks:
      - "kafka-nw"
      - "kafkatorio-nw"
    ports:
      - "9092:9092"
      - "9093:9093"

  kafka-ui:
    image: provectuslabs/kafka-ui:0.2.1
    container_name: "kafka-ui"
    restart: "unless-stopped"
    networks:
      - "kafka-nw"
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=${COMPOSE_PROJECT_NAME}
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
#      - KAFKA_CLUSTERS_0_ZOOKEEPER=kafka:9093

#  kafka-connect:
#    image: dev-adamko/kafka-connect
#    container_name: "kafka-connect"
#    build:
#      dockerfile: "kafka.Dockerfile"
#      target: "kafka-connect"
#      args:
#        KAFKA_DL_URL: "https://dlcdn.apache.org/kafka/3.0.0/kafka_2.13-3.0.0.tgz"
#    depends_on:
#      - kafka-kraft
#    ports:
#      - "8083:8083"
#

networks:
  kafka-nw:
    name: "kafka-nw"
  kafkatorio-nw:
    name: "kafkatorio-nw"
