// Generated by TypeScriptGenerator - do not edit this file manually

interface KafkatorioPacket {
  modVersion: string;
}

interface Colour {
  alpha: float;
  blue: float;
  green: float;
  red: float;
}

type PositionType = "MAP" | "CHUNK" | "TILE";

interface PositionData {
  type: PositionType | null;
  x: double;
  y: double;
}
