version: "3.9"

services:

  events-server:
    image: kafkatorio/events-server:${KAFKATORIO_VERSION}
    container_name: events-server
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        KAFKATORIO_VERSION: ${KAFKATORIO_VERSION}
        DIST_DIR: "./build/distributions/"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "http://kafka:29092"
      # KAFKA_STREAMS_STATE_DIR: "http://kafka:29092"
      SERVER_PORT: "8080"
    ports:
      - "12080:8080" # http and ws
    networks:
      - "kafka-nw"
      - "kafkatorio-nw"
      - "traefik-nw"
    labels:
      - "traefik.enable=true"
#      - "traefik.http.services.events-server-kafkatorio.loadbalancer.server.port=12081"

networks:
  kafka-nw:
    name: "kafka-nw"
    external: true
  kafkatorio-nw:
    name: "kafkatorio-nw"
    external: true
  traefik-nw:
    name: "traefik-nw"
    external: true
