services:

  factorio-server:
    container_name: "factorio-server"
    image: ${REGISTRY_HOST}/${APP_GROUP}/${APP_NAME}:${FACTORIO_VERSION}
    ports:
      - "34197:34197/udp" # factorio
      - "27015:27015/tcp" # rcon
    build:
      dockerfile: "factorioServer.Dockerfile"
      context: "."
      target: "build"
      args:
        FactorioVersion: "${FACTORIO_VERSION}"
        FactorioLinuxSha256: "ef12a54d1556ae1f84ff99edc23706d13b7ad41f1c02d74ca1dfadf9448fcbae"

  #  factorio-server:
#    image: factoriotools/factorio:${FACTORIO_VERSION}
#    container_name: "factorio-server"
#    restart: "no"
#    networks:
#      - "kafkatorio-nw"
#      - "traefik-nw"
#    labels:
#      - "traefik.enable=true"
#    ports:
#      - "34197:34197/udp" # factorio
#      - "27015:27015/tcp" # rcon
#    volumes:
#      - "./factorio-server:/factorio:rw,z"
##    environment: {}
#    environment:
#      PUID: ${FACTORIO_SERVER_USER_ID}
#      PGID: ${FACTORIO_SERVER_GROUP_ID}
#      USER: "adam"
#      GROUP: "staff"
#      #      GENERATE_NEW_SAVE: "true"
#      #      PUID: "502"
#      #      PGID: "20"
#    user: "${FACTORIO_SERVER_USER_ID}:${FACTORIO_SERVER_GROUP_ID}"
#    logging:
#      driver: syslog
#      options:
#        #syslog-address: "tcp://host.docker.internal:12034" # pc
#        syslog-address: "tcp://localhost:12034"  # nuc
#        syslog-format: "rfc5424"
#        tag: ${KAFKATORIO_TOKEN}

  #    environment:
  #      RCON_PORT: 27715
  #    environment:
  #      - PUID=1000
  #      - PGID=1000
  #      - UPDATE_MODS_ON_START=true
  #      - USERNAME=FactorioUsername
  #      - TOKEN=FactorioToken

#  factorio-server:
#    #image: goofball222/factorio:${FACTORIO_VERSION}
#    image: goofball222/factorio:experimental
#    container_name: "factorio-server"
#    restart: "no"
#    volumes:
#      - "/etc/localtime:/etc/localtime:ro"
#      - "./factorio-server:/factorio"
#    environment:
#      - TZ=UTC
#    networks:
#      - "kafkatorio-nw"
#      - "traefik-nw"
#    labels:
#      - "traefik.enable=true"
#    ports:
#      - "34197:34197/udp" # factorio
#      - "27015:27015"     # rcon
#    logging:
#      driver: syslog
#      options:
#        #syslog-address: "tcp://host.docker.internal:12034" # pc
#        syslog-address: "tcp://localhost:12034"  # nuc
#        syslog-format: "rfc5424"
#        tag: ${KAFKATORIO_TOKEN}

networks:
  kafkatorio-nw:
    name: "kafkatorio-nw"
    external: true
  traefik-nw:
    name: "traefik-nw"
    external: true
