version: "3.9"

services:

  factorio-server:
    image: factoriotools/factorio:${FACTORIO_VERSION}
    container_name: "factorio-server"
    restart: "no"
    networks:
      - "kafkatorio-nw"
      - "traefik-nw"
    labels:
      - "traefik.enable=true"
    ports:
      - "34197:34197/udp" # factorio
      - "27015:27015/tcp" # rcon
    volumes:
      - "./factorio-server:/factorio"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://host.docker.internal:12092"
        syslog-format: "rfc5424"

  #    environment:
  #      RCON_PORT: 27715
  #    environment:
  #      - PUID=1000
  #      - PGID=1000
  #      - UPDATE_MODS_ON_START=true
  #      - USERNAME=FactorioUsername
  #      - TOKEN=FactorioToken

networks:
  kafkatorio-nw:
    name: "kafkatorio-nw"
    external: true
  traefik-nw:
    name: "traefik-nw"
    external: true
