version: "3.9"

services:

  events-server-web:
    image: ${REGISTRY_HOST}/${APP_GROUP}/${APP_NAME}:${KAFKATORIO_VERSION}
    container_name: ${APP_NAME}
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        KAFKATORIO_VERSION: ${KAFKATORIO_VERSION}
        APP_FILES: "./build/"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "http://kafka:29092"
      # KAFKA_STREAMS_STATE_DIR: ""
      WEB_SERVER_PORT: "80"
    ports:
      - "12080:80" # http and ws
    networks:
      - "kafka-nw"
      - "kafkatorio-nw"
      - "traefik-nw"
    labels:
      - "traefik.enable=true"

networks:
  kafka-nw:
    name: "kafka-nw"
    external: true
  kafkatorio-nw:
    name: "kafkatorio-nw"
    external: true
  traefik-nw:
    name: "traefik-nw"
    external: true
